WORD_DICT = {
    # ============================================
    #  PART 1: Easy Words (Commonly Mispronounced)
    # ============================================
    "idea": ["ai", "d", "i", "a"],
    "focus": ["f", "o", "k", "a", "s"],
    "example": ["i", "g", "z", "a", "m", "p", "l"],
    "library": ["l", "ai", "b", "r", "e", "r", "i"],
    "clothes": ["k", "l", "o", "dh", "z"],
    "purpose": ["p", "r", "p", "a", "s"],
    "control": ["k", "a", "n", "t", "r", "o", "l"],
    "machine": ["m", "a", "sh", "i", "n"],
    "language": ["l", "a", "ng", "g", "w", "i", "j"],
    "support": ["s", "a", "p", "o", "r", "t"],

    # ============================================
    #  PART 2: Daily Use Words
    # ============================================
    "hello": ["h", "e", "l", "o"],
    "water": ["w", "o", "t", "r"],
    "beautiful": ["b", "y", "u", "t", "i", "f", "a", "l"],
    "important": ["i", "m", "p", "o", "r", "t", "a", "n", "t"],
    "different": ["d", "i", "f", "r", "a", "n", "t"],
    "together": ["t", "a", "g", "e", "dh", "r"],
    "tomorrow": ["t", "a", "m", "o", "r", "o"],
    "question": ["k", "w", "e", "s", "ch", "a", "n"],
    "answer": ["a", "n", "s", "r"],
    "problem": ["p", "r", "o", "b", "l", "a", "m"],
    "special": ["s", "p", "e", "sh", "a", "l"],
    "general": ["j", "e", "n", "r", "a", "l"],
    "natural": ["n", "a", "ch", "r", "a", "l"],
    "possible": ["p", "o", "s", "a", "b", "l"],
    "country": ["k", "a", "n", "t", "r", "i"],
    "people": ["p", "i", "p", "a", "l"],
    "family": ["f", "a", "m", "a", "l", "i"],
    "company": ["k", "a", "m", "p", "a", "n", "i"],
    "student": ["s", "t", "u", "d", "a", "n", "t"],
    "teacher": ["t", "i", "ch", "r"],

    # ============================================
    #  PART 3: Tricky Pronunciation Words
    # ============================================
    "colonel": ["k", "r", "n", "a", "l"],
    "recipe": ["r", "e", "s", "a", "p", "i"],
    "vegetable": ["v", "e", "j", "t", "a", "b", "a", "l"],
    "comfortable": ["k", "a", "m", "f", "r", "t", "a", "b", "a", "l"],
    "wednesday": ["w", "e", "n", "z", "d", "e"],
    "february": ["f", "e", "b", "r", "u", "e", "r", "i"],
    "schedule": ["sh", "e", "j", "u", "l"],
    "determine": ["d", "i", "t", "r", "m", "i", "n"],
    "temperature": ["t", "e", "m", "p", "r", "a", "ch", "r"],
    "chocolate": ["ch", "o", "k", "l", "a", "t"],
    "pronunciation": ["p", "r", "a", "n", "a", "n", "s", "i", "e", "sh", "a", "n"],
    "environment": ["i", "n", "v", "ai", "r", "a", "n", "m", "a", "n", "t"],
    "experience": ["i", "k", "s", "p", "i", "r", "i", "a", "n", "s"],
    "restaurant": ["r", "e", "s", "t", "r", "o", "n", "t"],
    "technology": ["t", "e", "k", "n", "o", "l", "a", "j", "i"],
    "government": ["g", "a", "v", "r", "n", "m", "a", "n", "t"],
    "education": ["e", "j", "u", "k", "e", "sh", "a", "n"],
    "information": ["i", "n", "f", "r", "m", "e", "sh", "a", "n"],
    "communicate": ["k", "a", "m", "y", "u", "n", "a", "k", "e", "t"],
    "opportunity": ["o", "p", "r", "t", "u", "n", "a", "t", "i"],

    # ============================================
    #  PART 4: Professional / IELTS Words
    # ============================================
    "analyze": ["a", "n", "a", "l", "ai", "z"],
    "develop": ["d", "i", "v", "e", "l", "a", "p"],
    "achieve": ["a", "ch", "i", "v"],
    "knowledge": ["n", "o", "l", "i", "j"],
    "necessary": ["n", "e", "s", "a", "s", "e", "r", "i"],
    "available": ["a", "v", "e", "l", "a", "b", "a", "l"],
    "situation": ["s", "i", "ch", "u", "e", "sh", "a", "n"],
    "community": ["k", "a", "m", "y", "u", "n", "a", "t", "i"],
    "interview": ["i", "n", "t", "r", "v", "y", "u"],
    "absolutely": ["a", "b", "s", "a", "l", "u", "t", "l", "i"],
    "appreciate": ["a", "p", "r", "i", "sh", "i", "e", "t"],
    "challenge": ["ch", "a", "l", "a", "n", "j"],
    "character": ["k", "e", "r", "a", "k", "t", "r"],
    "creative": ["k", "r", "i", "e", "t", "i", "v"],
    "decision": ["d", "i", "s", "i", "zh", "a", "n"],
    "excellent": ["e", "k", "s", "a", "l", "a", "n", "t"],
    "imagine": ["i", "m", "a", "j", "i", "n"],
    "industry": ["i", "n", "d", "a", "s", "t", "r", "i"],
    "management": ["m", "a", "n", "i", "j", "m", "a", "n", "t"],
    "organize": ["o", "r", "g", "a", "n", "ai", "z"],
    "personal": ["p", "r", "s", "a", "n", "a", "l"],
    "practice": ["p", "r", "a", "k", "t", "i", "s"],
    "research": ["r", "i", "s", "r", "ch"],
    "success": ["s", "a", "k", "s", "e", "s"],
    "consider": ["k", "a", "n", "s", "i", "d", "r"],

    # ============================================
    #  PART 5: Common Indian Mispronunciation Words
    # ============================================
    "think": ["th", "i", "ng", "k"],
    "this": ["dh", "i", "s"],
    "that": ["dh", "a", "t"],
    "three": ["th", "r", "i"],
    "the": ["dh", "a"],
    "there": ["dh", "e", "r"],
    "them": ["dh", "e", "m"],
    "these": ["dh", "i", "z"],
    "those": ["dh", "o", "z"],
    "with": ["w", "i", "dh"],
    "weather": ["w", "e", "dh", "r"],
    "father": ["f", "a", "dh", "r"],
    "mother": ["m", "a", "dh", "r"],
    "brother": ["b", "r", "a", "dh", "r"],
    "other": ["a", "dh", "r"],
    "another": ["a", "n", "a", "dh", "r"],
    "thank": ["th", "a", "ng", "k"],
    "thought": ["th", "o", "t"],
    "through": ["th", "r", "u"],
    "throw": ["th", "r", "o"],
    "month": ["m", "a", "n", "th"],
    "south": ["s", "au", "th"],
    "north": ["n", "o", "r", "th"],
    "birth": ["b", "r", "th"],
    "worth": ["w", "r", "th"],
    "earth": ["r", "th"],
    "health": ["h", "e", "l", "th"],
    "wealth": ["w", "e", "l", "th"],
    "bath": ["b", "a", "th"],
    "path": ["p", "a", "th"],
    "math": ["m", "a", "th"],

    # ============================================
    #  PART 6: V/W Confusion Words
    # ============================================
    "very": ["v", "e", "r", "i"],
    "village": ["v", "i", "l", "i", "j"],
    "voice": ["v", "oi", "s"],
    "value": ["v", "a", "l", "y", "u"],
    "video": ["v", "i", "d", "i", "o"],
    "view": ["v", "y", "u"],
    "visit": ["v", "i", "z", "i", "t"],
    "various": ["v", "e", "r", "i", "a", "s"],
    "version": ["v", "r", "zh", "a", "n"],
    "volume": ["v", "o", "l", "y", "u", "m"],
    "wine": ["w", "ai", "n"],
    "world": ["w", "r", "l", "d"],
    "work": ["w", "r", "k"],
    "west": ["w", "e", "s", "t"],
    "woman": ["w", "u", "m", "a", "n"],
    "wonder": ["w", "a", "n", "d", "r"],
    "window": ["w", "i", "n", "d", "o"],
    "wish": ["w", "i", "sh"],
    "wait": ["w", "e", "t"],
    "walk": ["w", "o", "k"],

    # ============================================
    #  PART 7: IELTS / Academic Words
    # ============================================
    "hypothesis": ["h", "ai", "p", "o", "th", "a", "s", "i", "s"],
    "phenomenon": ["f", "a", "n", "o", "m", "a", "n", "o", "n"],
    "analysis": ["a", "n", "a", "l", "a", "s", "i", "s"],
    "significant": ["s", "i", "g", "n", "i", "f", "i", "k", "a", "n", "t"],
    "consequence": ["k", "o", "n", "s", "a", "k", "w", "a", "n", "s"],
    "perspective": ["p", "r", "s", "p", "e", "k", "t", "i", "v"],
    "authority": ["a", "th", "o", "r", "a", "t", "i"],
    "particularly": ["p", "r", "t", "i", "k", "y", "a", "l", "r", "l", "i"],
    "infrastructure": ["i", "n", "f", "r", "a", "s", "t", "r", "a", "k", "ch", "r"],
    "entrepreneur": ["o", "n", "t", "r", "a", "p", "r", "a", "n", "r"],
    "architecture": ["a", "r", "k", "a", "t", "e", "k", "ch", "r"],
    "certificate": ["s", "r", "t", "i", "f", "a", "k", "a", "t"],
    "administration": ["a", "d", "m", "i", "n", "i", "s", "t", "r", "e", "sh", "a", "n"],
    "professional": ["p", "r", "a", "f", "e", "sh", "a", "n", "a", "l"],
    "international": ["i", "n", "t", "r", "n", "a", "sh", "a", "n", "a", "l"],
    "communication": ["k", "a", "m", "y", "u", "n", "a", "k", "e", "sh", "a", "n"],
    "understanding": ["a", "n", "d", "r", "s", "t", "a", "n", "d", "i", "ng"],
    "responsibility": ["r", "i", "s", "p", "o", "n", "s", "a", "b", "i", "l", "a", "t", "i"],
    "organization": ["o", "r", "g", "a", "n", "ai", "z", "e", "sh", "a", "n"],
    "approximately": ["a", "p", "r", "o", "k", "s", "a", "m", "a", "t", "l", "i"],

    # ============================================
    #  PART 8: Common Daily Conversation Words
    # ============================================
    "about": ["a", "b", "au", "t"],
    "again": ["a", "g", "e", "n"],
    "always": ["o", "l", "w", "e", "z"],
    "because": ["b", "i", "k", "o", "z"],
    "before": ["b", "i", "f", "o", "r"],
    "begin": ["b", "i", "g", "i", "n"],
    "between": ["b", "i", "t", "w", "i", "n"],
    "change": ["ch", "e", "n", "j"],
    "children": ["ch", "i", "l", "d", "r", "a", "n"],
    "city": ["s", "i", "t", "i"],
    "close": ["k", "l", "o", "z"],
    "complete": ["k", "a", "m", "p", "l", "i", "t"],
    "continue": ["k", "a", "n", "t", "i", "n", "y", "u"],
    "correct": ["k", "a", "r", "e", "k", "t"],
    "could": ["k", "u", "d"],
    "create": ["k", "r", "i", "e", "t"],
    "during": ["d", "u", "r", "i", "ng"],
    "early": ["r", "l", "i"],
    "enjoy": ["i", "n", "j", "oi"],
    "enough": ["i", "n", "a", "f"],
    "every": ["e", "v", "r", "i"],
    "explain": ["i", "k", "s", "p", "l", "e", "n"],
    "finish": ["f", "i", "n", "i", "sh"],
    "first": ["f", "r", "s", "t"],
    "friend": ["f", "r", "e", "n", "d"],
    "future": ["f", "y", "u", "ch", "r"],
    "great": ["g", "r", "e", "t"],
    "group": ["g", "r", "u", "p"],
    "happy": ["h", "a", "p", "i"],
    "hear": ["h", "i", "r"],
    "history": ["h", "i", "s", "t", "r", "i"],
    "house": ["h", "au", "s"],
    "however": ["h", "au", "e", "v", "r"],
    "human": ["h", "y", "u", "m", "a", "n"],
    "include": ["i", "n", "k", "l", "u", "d"],
    "increase": ["i", "n", "k", "r", "i", "s"],
    "interest": ["i", "n", "t", "r", "a", "s", "t"],
    "issue": ["i", "sh", "u"],
    "large": ["l", "a", "r", "j"],
    "learn": ["l", "r", "n"],
    "little": ["l", "i", "t", "a", "l"],
    "local": ["l", "o", "k", "a", "l"],
    "market": ["m", "a", "r", "k", "a", "t"],
    "matter": ["m", "a", "t", "r"],
    "measure": ["m", "e", "zh", "r"],
    "minute": ["m", "i", "n", "a", "t"],
    "modern": ["m", "o", "d", "r", "n"],
    "money": ["m", "a", "n", "i"],
    "morning": ["m", "o", "r", "n", "i", "ng"],
    "music": ["m", "y", "u", "z", "i", "k"],
    "national": ["n", "a", "sh", "a", "n", "a", "l"],
    "nature": ["n", "e", "ch", "r"],
    "never": ["n", "e", "v", "r"],
    "number": ["n", "a", "m", "b", "r"],
    "office": ["o", "f", "i", "s"],
    "often": ["o", "f", "a", "n"],
    "picture": ["p", "i", "k", "ch", "r"],
    "place": ["p", "l", "e", "s"],
    "please": ["p", "l", "i", "z"],
    "present": ["p", "r", "e", "z", "a", "n", "t"],
    "produce": ["p", "r", "a", "d", "u", "s"],
    "program": ["p", "r", "o", "g", "r", "a", "m"],
    "provide": ["p", "r", "a", "v", "ai", "d"],
    "public": ["p", "a", "b", "l", "i", "k"],
    "really": ["r", "i", "l", "i"],
    "reason": ["r", "i", "z", "a", "n"],
    "receive": ["r", "i", "s", "i", "v"],
    "record": ["r", "e", "k", "r", "d"],
    "report": ["r", "i", "p", "o", "r", "t"],
    "result": ["r", "i", "z", "a", "l", "t"],
    "return": ["r", "i", "t", "r", "n"],
    "school": ["s", "k", "u", "l"],
    "science": ["s", "ai", "a", "n", "s"],
    "service": ["s", "r", "v", "a", "s"],
    "simple": ["s", "i", "m", "p", "a", "l"],
    "society": ["s", "a", "s", "ai", "a", "t", "i"],
    "something": ["s", "a", "m", "th", "i", "ng"],
    "sometimes": ["s", "a", "m", "t", "ai", "m", "z"],
    "strong": ["s", "t", "r", "o", "ng"],
    "system": ["s", "i", "s", "t", "a", "m"],
    "table": ["t", "e", "b", "a", "l"],
    "today": ["t", "a", "d", "e"],
    "travel": ["t", "r", "a", "v", "a", "l"],
    "trouble": ["t", "r", "a", "b", "a", "l"],
    "under": ["a", "n", "d", "r"],
    "usually": ["y", "u", "zh", "u", "a", "l", "i"],
    "value": ["v", "a", "l", "y", "u"],
    "whether": ["w", "e", "dh", "r"],
    "without": ["w", "i", "dh", "au", "t"],
    "young": ["y", "a", "ng"],

    # ============================================
    #  PART 9: Easy Sentences
    # ============================================
    "i have a good idea": ["ai", "h", "a", "v", "a", "g", "u", "d", "ai", "d", "i", "a"],
    "focus on your work": ["f", "o", "k", "a", "s", "o", "n", "y", "o", "r", "w", "r", "k"],
    "give me an example": ["g", "i", "v", "m", "i", "a", "n", "i", "g", "z", "a", "m", "p", "l"],
    "go to the library": ["g", "o", "t", "u", "dh", "a", "l", "ai", "b", "r", "e", "r", "i"],
    "wash your clothes": ["w", "o", "sh", "y", "o", "r", "k", "l", "o", "dh", "z"],
    "good morning": ["g", "u", "d", "m", "o", "r", "n", "i", "ng"],
    "see you later": ["s", "i", "y", "u", "l", "e", "t", "r"],
    "excuse me": ["i", "k", "s", "k", "y", "u", "z", "m", "i"],
    "i am sorry": ["ai", "a", "m", "s", "o", "r", "i"],
    "no problem": ["n", "o", "p", "r", "o", "b", "l", "a", "m"],

    # ============================================
    #  PART 10: Medium Sentences
    # ============================================
    "what is the purpose": ["w", "a", "t", "i", "z", "dh", "a", "p", "r", "p", "a", "s"],
    "control the system": ["k", "a", "n", "t", "r", "o", "l", "dh", "a", "s", "i", "s", "t", "e", "m"],
    "turn on the machine": ["t", "r", "n", "o", "n", "dh", "a", "m", "a", "sh", "i", "n"],
    "english is a language": ["i", "ng", "g", "l", "i", "sh", "i", "z", "a", "l", "a", "ng", "g", "w", "i", "j"],
    "i support this project": ["ai", "s", "a", "p", "o", "r", "t", "dh", "i", "s", "p", "r", "o", "j", "e", "k", "t"],
    "please close the door": ["p", "l", "i", "z", "k", "l", "o", "z", "dh", "a", "d", "o", "r"],
    "i need some water": ["ai", "n", "i", "d", "s", "a", "m", "w", "o", "t", "r"],
    "what time is it": ["w", "a", "t", "t", "ai", "m", "i", "z", "i", "t"],
    "where is the office": ["w", "e", "r", "i", "z", "dh", "a", "o", "f", "i", "s"],
    "can i help you": ["k", "a", "n", "ai", "h", "e", "l", "p", "y", "u"],

    # ============================================
    #  PART 11: Daily Conversation Sentences
    # ============================================
    "how are you": ["h", "au", "o", "r", "y", "u"],
    "nice to meet you": ["n", "ai", "s", "t", "u", "m", "i", "t", "y", "u"],
    "thank you very much": ["th", "a", "ng", "k", "y", "u", "v", "e", "r", "i", "m", "a", "ch"],
    "what is your name": ["w", "a", "t", "i", "z", "y", "o", "r", "n", "e", "m"],
    "where do you live": ["w", "e", "r", "d", "u", "y", "u", "l", "i", "v"],
    "i am a student": ["ai", "a", "m", "a", "s", "t", "u", "d", "a", "n", "t"],
    "can you help me": ["k", "a", "n", "y", "u", "h", "e", "l", "p", "m", "i"],
    "i like this place": ["ai", "l", "ai", "k", "dh", "i", "s", "p", "l", "e", "s"],
    "let me think about it": ["l", "e", "t", "m", "i", "th", "i", "ng", "k", "a", "b", "au", "t", "i", "t"],
    "have a good day": ["h", "a", "v", "a", "g", "u", "d", "d", "e"],

    # ============================================
    #  PART 12: Professional / Interview Sentences
    # ============================================
    "tell me about yourself": ["t", "e", "l", "m", "i", "a", "b", "au", "t", "y", "o", "r", "s", "e", "l", "f"],
    "i want to improve": ["ai", "w", "o", "n", "t", "t", "u", "i", "m", "p", "r", "u", "v"],
    "this is very important": ["dh", "i", "s", "i", "z", "v", "e", "r", "i", "i", "m", "p", "o", "r", "t", "a", "n", "t"],
    "i need more practice": ["ai", "n", "i", "d", "m", "o", "r", "p", "r", "a", "k", "t", "i", "s"],
    "the weather is nice today": ["dh", "a", "w", "e", "dh", "r", "i", "z", "n", "ai", "s", "t", "a", "d", "e"],
    "i have a question": ["ai", "h", "a", "v", "a", "k", "w", "e", "s", "ch", "a", "n"],
    "what do you think": ["w", "a", "t", "d", "u", "y", "u", "th", "i", "ng", "k"],
    "i appreciate your help": ["ai", "a", "p", "r", "i", "sh", "i", "e", "t", "y", "o", "r", "h", "e", "l", "p"],
    "this is a great opportunity": ["dh", "i", "s", "i", "z", "a", "g", "r", "e", "t", "o", "p", "r", "t", "u", "n", "a", "t", "i"],
    "i would like to apply": ["ai", "w", "u", "d", "l", "ai", "k", "t", "u", "a", "p", "l", "ai"],

    # ============================================
    #  PART 13: Advanced / Challenging Sentences
    # ============================================
    "the environment needs protection": ["dh", "a", "i", "n", "v", "ai", "r", "a", "n", "m", "a", "n", "t", "n", "i", "d", "z", "p", "r", "a", "t", "e", "k", "sh", "a", "n"],
    "education is the key to success": ["e", "j", "u", "k", "e", "sh", "a", "n", "i", "z", "dh", "a", "k", "i", "t", "u", "s", "a", "k", "s", "e", "s"],
    "technology is changing the world": ["t", "e", "k", "n", "o", "l", "a", "j", "i", "i", "z", "ch", "e", "n", "j", "i", "ng", "dh", "a", "w", "r", "l", "d"],
    "communication is very important": ["k", "a", "m", "y", "u", "n", "a", "k", "e", "sh", "a", "n", "i", "z", "v", "e", "r", "i", "i", "m", "p", "o", "r", "t", "a", "n", "t"],
    "i want to learn english": ["ai", "w", "o", "n", "t", "t", "u", "l", "r", "n", "i", "ng", "g", "l", "i", "sh"],
}